# Generated by Django 5.0.7 on 2025-08-26 04:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='VendorProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('business_name', models.CharField(max_length=120)),
                ('location', models.CharField(max_length=120)),
                ('description', models.TextField(blank=True)),
                ('contact_phone', models.CharField(max_length=30)),
                ('shop_type', models.CharField(choices=[('physical', 'Physical'), ('digital', 'Digital'), ('both', 'Both')], default='physical', max_length=10)),
                ('whatsapp_number', models.CharField(blank=True, max_length=30)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='vendor_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
